// Code generated by smithy-go-codegen DO NOT EDIT.

package simpleconstraintstypes

import (
	"fmt"
)

type SimpleConstraintsException struct {
	SimpleConstraintsBaseException
	Message *string

	ErrorCodeOverride *string
}

func (e SimpleConstraintsException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCodeOverride, e.Message)
}
