// Code generated by smithy-go-codegen DO NOT EDIT.

package simpleconstraints

import (
	"context"

	"github.com/Smithy-dafny/TestModels/Constraints/simpleconstraintsinternaldafny"
	"github.com/Smithy-dafny/TestModels/Constraints/simpleconstraintsinternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/Constraints/simpleconstraintstypes"
)

type Client struct {
	DafnyClient *simpleconstraintsinternaldafny.SimpleConstraintsClient
}

func NewClient(clientConfig simpleconstraintstypes.SimpleConstraintsConfig) (*Client, error) {
	var dafnyConfig = SimpleConstraintsConfig_ToDafny(clientConfig)
	var dafny_response = simpleconstraintsinternaldafny.Companion_Default___.SimpleConstraints(dafnyConfig)
	if dafny_response.Is_Failure() {
		panic("Client construction failed. This should never happen")
	}
	var dafnyClient = dafny_response.Extract().(*simpleconstraintsinternaldafny.SimpleConstraintsClient)
	client := &Client{dafnyClient}
	return client, nil
}

func (client *Client) GetConstraints(ctx context.Context, params simpleconstraintstypes.GetConstraintsInput) (*simpleconstraintstypes.GetConstraintsOutput, error) {
	err := params.Validate()
	if err != nil {
		return nil, err
	}
	var dafny_request simpleconstraintsinternaldafnytypes.GetConstraintsInput = GetConstraintsInput_ToDafny(params)
	var dafny_response = client.DafnyClient.GetConstraints(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simpleconstraintsinternaldafnytypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetConstraintsOutput_FromDafny(dafny_response.Extract().(simpleconstraintsinternaldafnytypes.GetConstraintsOutput))
	return &native_response, nil

}
